module.exports = {
    handlerAuth: require('./handlerAuth'),
    handlerRegister: require('./handlerRegister'),
    handlerRetrieveUser: require('./handlerRetrieveUser'),
    handlerUpdateUserName: require('./handlerUpdateUserName'),
    handlerUpdateUserEmail: require('./handlerUpdateUserEmail'),
    handlerUpdateUserPassword: require('./handlerUpdateUserPassword'),
    handlerCreateTask: require('./handlerCreateTask'),
    handlerRetrieveTasks: require('./handlerRetrieveTasks'),
    handlerDeleteTask: require('./handlerDeleteTask'),
    handlerUpdateTaskStatus: require('./handlerUpdateTaskStatus'),
    handlerUpdateTaskText: require('./handlerUpdateTaskText'),
    handlerUpdateTaskTitle: require('./handlerUpdateTaskTitle'),
    handlerCreatePost: require('./handlerCreatePost'),
    handlerRetrievePublicPosts: require('./handlerRetrievePublicPosts'),
    handlerRetrievePost: require('./handlerRetrievePost'),
    handlerDeletePost: require('./handlerDeletePost'),
    handlerUpdatePost: require('./handlerUpdatePost'),
    handlerRetrieveAUser: require('./handlerRetrieveAUser'),
    handlerRetrievePostsFromUser: require('./handlerRetrievePostsFromUser')
}