module.exports = {
    handlerAuth: require('./handlerAuth'),
    handlerRegister: require('./handlerRegister'),
    handlerRetrieveUser: require('./handlerRetrieveUser'),
    handlerUpdateUserName: require('./handlerUpdateUserName'),
    handlerUpdateUserEmail: require('./handlerUpdateUserEmail'),
    handlerUpdateUserPassword: require('./handlerUpdateUserPassword'),
    handlerCreateTask: require('./handlerCreateTask'),
    handlerRetrieveTasks: require('./handlerRetrieveTasks'),
    handlerDeleteTask: require('./handlerDeleteTask'),
    handlerUpdateTaskStatus: require('./handlerUpdateTaskStatus'),
    handlerUpdateTaskText: require('./handlerUpdateTaskText'),
    handlerUpdateTaskTitle: require('./handlerUpdateTaskTitle'),
    handlerCreatePost: require('./handlerCreatePost'),
    handlerRetrievePosts: require('./handlerRetrievePosts'),
    handlerDeletePost: require('./handlerDeletePost'),
    handlerUpdatePostText: require('./handlerUpdatePostText'),
    handlerUpdatePostVisibility: require('./handlerUpdatePostVisibility'),
    searchGet: require('./searchGet')
}